Check for minimum screen size at startup
If the screen has too few lines or columns to display all of the windows
entirely, TextPad.refresh will crash with the following error:

Traceback (most recent call last):
  File "meshtastic/meshwatch/meshwatch.py", line 431, in Clear
    self.TextPad.refresh(0,0,self.y1,self.x1,self.y1 + self.rows,self.x1 + self.columns)
_curses.error: prefresh() returned ERR

A nice solution would be to rescale the windows according to the screen
size but as a first measure, quit gracefully instead of crashing. This
change does not protect against users shrinking their console or
increasing font size after startup
(cf. https://github.com/datagod/meshwatch/issues/8)

Fixes https://github.com/datagod/meshwatch/issues/11